[package]
name = "scripts-executor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "executor"
path = "executor.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

