[package]
name = "excelparser"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.30.1"
chrono = "0.4.42"
clap = { version = "4.5.47", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
